In [2]:
#Задание №1
def fib(N, c = {0:0, 1:1}):
    if N in c:
        return(c[N])
    else:
        c[N-1] = fib(N-1)
        c[N-2] = fib(N-2)
        return fib(N-1, c) + fib(N-2, c)
print(fib(6))

8


In [3]:
#Задание №2
n = int(input())
mn = []
def prost(n):
    if n != 1:
        for i in range(2, n+1):
            if n % i == 0:
                mn.append(i)
                prost(n//i)
                break
prost(n)
print(mn)

 55


[5, 11]


In [35]:
#Задание №3
def gcd(a, b):
    if a == 0 or b == 0: 
         return max(a, b)
    else:
        if a > b:
            return gcd(a - b, b)
        else:
            return gcd(a, b - a)

def ads(a):
    if a < 0:
        a = -a
    return a

a, b = int(input()), int(input())
g = gcd(a, b)
s = 99999
for i in range(-a, a):
    for q in range(-b, b):
        if i*a+q*b == g:
            if ( ads(i) + ads(q) ) < s:
                i_1 = i
                q_1 = q
                s = ads(i) + ads(q)
            elif ( ads(i) + ads(q) ) == s and i < i_1:
                i_1 = i
                q_1 = q
                s = ads(i) + ads(q)
print(i_1, q_1, g)

 17
 17


0 1 17


In [15]:
#Задание №4
size = int(input())
symb = str(input())

for i in range(1, size//2+(size%2)+1):
    print(symb*i)
for q in range(size//2, 0, -1):
    print(symb*q)

 9
 с


с
сс
ссс
сссс
ссссс
сссс
ссс
сс
с


In [4]:
#Задание №5
import numpy as np
def sm(N, M):
    left, top, bottom, right = 0, 0, N, M
    res = np.zeros((N, M))

    num = 1
    while left < right and top < bottom:
        res[top, left:right] = np.arange( num, num + right - left)
        num += right - left

        top += 1
        res[top:bottom, right - 1] = np.arange( num, num+bottom - top)
        num += bottom - top
        right -= 1

        if not (left < right and top < bottom):
            break

        res[bottom - 1, left:right][::-1] = np.arange(num, num + right - left)
        num += right - left
        bottom -= 1

        res[top:bottom, left][::-1] = np. arange(num, num + bottom - top)
        num += bottom - top
        left += 1
    return res
   
N, M = int(input()), int(input())
print(sm(N, M))

 5
 6


[[ 1.  2.  3.  4.  5.  6.]
 [18. 19. 20. 21. 22.  7.]
 [17. 28. 29. 30. 23.  8.]
 [16. 27. 26. 25. 24.  9.]
 [15. 14. 13. 12. 11. 10.]]


In [1]:
#Задание №6
import numpy as np

def MNK(x, y):
    x_mean = np.mean(x)
    y_mean = np.mean(y)

    m = np.sum((x - x_mean) * (y - y_mean))/np.sum((x - x_mean)**2)
    b = y_mean - m * x_mean
    return m, b

#Пример
a = [1, 3, 5, 6, 8, 9]
b = [2, 4, 7, 8, 12, 14]
print(MNK(a, b))

(np.float64(1.507352941176471), np.float64(-0.2058823529411784))
